### ISSUE TITLE
Dates seem to be backwards?

### ISSUE THREAD

**Issue by acournoyer1** [Detaysoft/react-chat-elements#100]
Dates in the past seem to say the message is coming up, and dates in the future say the date is in the past.
![66668393_467464527387345_1025016008437399552_n](https://user-images.githubusercontent.com/19155242/60918682-edffc300-a261-11e9-976a-7d17c302c75b.png)
![66505404_2753702931522642_5583450041621676032_n](https://user-images.githubusercontent.com/19155242/60918688-ef30f000-a261-11e9-8cc1-e8dcd4a93514.jpg)

**Comment by Goregut** [comment]
Just noticed this as well. I was on 10.5.0, then updated to latest and still seeing it. Reverted back to 10.2.0 and it's working like it should for me again. Thanks for spotting this @acournoyer1 ! Wouldn't have noticed until it was too late.

**Comment by abdurrahmanekr** [comment]
Fixed and published @10.7.1. Thanks @rorz for #101

**Comment by rorz** [comment]
No worries — glad to help this awesome lib! :)
