### ISSUE TITLE
MessageBox drawing black triangles

### ISSUE THREAD

**Issue by Pieter-JanLavaerts** [Detaysoft/react-chat-elements#109]
I'm trying to use the MessageBox component in my project but when rendering, the box shows up as a black triangle.
![2019-11-20-134954_1599x843_scrot](https://user-images.githubusercontent.com/42444653/69240288-6c6b5a80-0b9c-11ea-95c8-0a267aa0a378.png)
![2019-11-20-134832_331x249_scrot](https://user-images.githubusercontent.com/42444653/69240304-72f9d200-0b9c-11ea-8db9-e78cd5260594.png)

**Comment by abdurrahmanekr** [comment]
hi, did you include the css file? (ex: import '
react-chat-elements/dist/main.css';)

20 Kas 2019 Çar, saat ÖS 3:49 tarihinde Pieter-JanLavaerts <
notifications@github.com> şunu yazdı:

**Comment by Pieter-JanLavaerts** [comment]
Thank you that fixed the issue! :)
