### ISSUE TITLE
Html encode

### ISSUE THREAD

**Issue by thiagoarioli** [Detaysoft/react-chat-elements#114]
There is away to render html inside the text option?
For example in div we use:
<div className="font-12" dangerouslySetInnerHTML={{ __html: action.info }} />

Can we do this in text attribute?

Thanks

**Comment by abdurrahmanekr** [comment]
Example:
```javascript
<MessageBox
    type='text'
    text={<p>paragraph <b>bold value</b></p>}  />
```

If you want to use dangerouslySetInnerHTML:
```javascript
<MessageBox
    type='text'
    text={<div dangerouslySetInnerHTML={{__html: '<div><script>alert(\'hi madame\')</script></div>'}} />} />
```
