### ISSUE TITLE
How to send a voice message

### ISSUE THREAD

**Issue by cystudyeverday** [Detaysoft/react-chat-elements#116]
Thanks for providing useful tool.
I am new to the react. 
May i ask how can i present the voice message on the message list since the type "audio" does not exist?
I saw the props named "renderAddCmp" i guess i should use this but i dont know how.
Thanks for helping!!

**Comment by abdurrahmanekr** [comment]
Hi, it's best to add a component to do this, it would be nice if you or anyone opens PR for it.

but messageBox can be dynamized:

Example:
```javascript
<MessageBox
    type='text'
    text={(
      <audio controls>
        <source src="path/to/sound.ogg" type="audio/ogg">
        <source src="path/to/sound.mp3" type="audio/mpeg">
        Your browser does not support the audio element.
      </audio>
    )}
```
