### ISSUE TITLE
Do you have a little more documentation? How about styling the MessageList in React Native.

### ISSUE THREAD

**Issue by mitchobrian** [Detaysoft/react-chat-elements#121]
Do you have a short doc how to style the MessageList Component eg. the Background of the MessageBoxes or the Avatar styles and so on!?

**Comment by mitchobrian** [comment]
Also the behavior is different, this is how it looks in the react web app:
![image](https://user-images.githubusercontent.com/2011681/88270831-87b3da00-ccd6-11ea-9714-a99a9a3e9095.png)

This is the native appearance:
![image](https://user-images.githubusercontent.com/2011681/88270856-91d5d880-ccd6-11ea-92b4-d822375ae096.png)

**Comment by abdurrahmanekr** [comment]
It is currently on the react-native to-do list #61 . But we don't have much time.
