### ISSUE TITLE
Make MessageList to allow JSX as well

### ISSUE THREAD

**Issue by ilyaskarim** [Detaysoft/react-chat-elements#124]
When I use 

```javascript
const dataSource = props.messages.map((messageItem) => {
  return {
      position: messageItem.from == 'Contact' ? 'left' : 'right',
      type: 'text',
      text: () => {
        return <div>{messageItem.messageText}</div>
      },
      date: new Date(messageItem.createdAt),
  }
})
```

The text is empty inside MessageList component. But when I set: 

```javascript
const dataSource = props.messages.map((messageItem) => {
  return {
      position: messageItem.from == 'Contact' ? 'left' : 'right',
      type: 'text',
      text: messageItem.messageText,
      date: new Date(messageItem.createdAt),
  }
})
```

It works. Can we allow **text** to consider JSX as well?

**Comment by abdurrahmanekr** [comment]
Actually, there is already JSX support in the text. Don't give text a function. Give JSX directly. For example:

```javascript
const dataSource = props.messages.map((messageItem) => {
  return {
      position: messageItem.from == 'Contact' ? 'left' : 'right',
      type: 'text',
      text: <div>{messageItem.messageText}</div>,
      date: new Date(messageItem.createdAt),
  }
})
```

**Comment by christianfz** [comment]
Hello, thanks again for this package. We've been using this and it works great!

I know that this issue has been closed but when I try to assign a JSX on `text` I get this:

![image](https://github.com/Detaysoft/react-chat-elements/assets/130006043/cfba6aff-77f1-47b6-964d-3765f88c6077)

Is there a new way to accomplish this?

Thanks!

**Comment by christianfz** [comment]
Actually it still works if I added a `// @ts-ignore` on that line.
Maybe it's just a typing issue?
