### ISSUE TITLE
Message List component breaks

### ISSUE THREAD

**Issue by chloeblazey** [Detaysoft/react-chat-elements#142]
The message list component has a breaking bug. I believe it's because it uses string refs, and my project is using functional components.

It shows the following error:
Error: Element ref was specified as a string (message) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://reactjs.org/link/refs-must-have-owner for more information.

**Comment by YashTotale** [comment]
Having the same issue

**Comment by hashaaan** [comment]
Yes. I'm also having the same issue

**Comment by ALex-Hwang** [comment]
Having the same issue with the MessgeBox...

**Comment by janoist1** [comment]
+1 :(

**Comment by fapjsc** [comment]
+1. :(

**Comment by zahmadz** [comment]
Same issue with MessageBox

**Comment by emregudur** [comment]
Hi guys, this problem fixed on the new version. Checkout here pls [click](https://www.npmjs.com/package/react-chat-elements/v/11.0.0)
