### ISSUE TITLE
Image resizing, multiple images and onClick not working in MessageBox component

### ISSUE THREAD

**Issue by mp051998** [Detaysoft/react-chat-elements#149]
Is there a feature to resize the image in chat?

![image](https://user-images.githubusercontent.com/25613636/134443782-6f55731c-27f2-4e50-9c1a-85adcd8e2657.png)

I'm not able to resize it.
Also, I'm not able to get onClick to work for this either.
And yes, does the MessageBox Component support multiple files?

**Comment by abdurrahmanekr** [comment]
Hi,
> Is there a feature to resize the image in chat?

If your message type is 'photo' than it should be working success. ex: 

```javascript
<MessageBox
    position={'left'}
    type={'photo'}
    text={'react.svg'}
    onClick={console.log}
    data={{
        uri: '<your image uri>',
        status: {
            click: false,
            loading: 0,
        },
        width: 300,
        height: 300
    }}/>
```

**Comment by mp051998** [comment]
okay wow, this is awesome. Thanks! Would've been nice if you have like a bit of documentation for data too, nonetheless, this is great!

Any idea if there's support for multiple files in chat?

**Comment by abdurrahmanekr** [comment]
> Any idea if there's support for multiple files in chat?

No.

We would be grateful if you would like to help :)
