### ISSUE TITLE
Message box component not supporting video 

### ISSUE THREAD

**Issue by REEDOOX** [Detaysoft/react-chat-elements#150]
I'm trying to integrate the a video element in the chat with the following code 
```
<MessageBox
                position={message.incoming ? "left" : "right"}
                type={"video"}
                text={message.text}
                date={new Date(message.sentAt)}
                data={{
                  uri: "https://res.cloudinary.com/dmtgbbfs5/video/upload/v1632654825/zf9alfdmjuiuqihhayu5.mp4",
                  status: {
                    click: true,
                    loading: 0,
                  },
                  width: 300,
                  height: 300,
                }}
              />
```

The video does not show. The tag I see in the HTML is <img />

Edit, after adding download: true to status so the video appears grayed out

**Comment by abdurrahmanekr** [comment]
Our documentation is not good enough so if you are having a problem I think you can find it through the example directory. If you use `videoURL` instead of `uri` your problem will be solved.
