### ISSUE TITLE
Error in react-chat-elements-typescript library MessageBox component

### ISSUE THREAD

**Issue by NuwanF** [Detaysoft/react-chat-elements#155]
Invalid hook call error occurs when adding react-chat-elements-typescript library MessageBox component
https://reactjs.org/docs/error-decoder.html/?invariant=321

![image_2021_11_08T06_30_19_828Z](https://user-images.githubusercontent.com/26604944/140765113-6c74ad2b-9dd4-46f2-9c21-6f3a264a20d9.png)

**Comment by mp051998** [comment]
hi, can you show the code for this as well?

**Comment by NuwanF** [comment]
Sure. This error only exists with "MessageBox" component

`
import { MessageBox } from "react-chat-elements-typescript";

function App() {
    return (
        <div className="App">
            <MessageBox
                className="chat-color"
                title="Tobias"
                avatar={"https://cdn-icons-png.flaticon.com/512/727/727399.png"}
                onReplyMessageClick={() => console.log("reply clicked!")}
                position={"left"}
                type={"text"}
                text={
                    "Let me know once you complete."
                }
                replyButton={true}
                date={new Date()}
            />
        </div>
    );
}
`

**Comment by emregudur** [comment]
Hi, you can use just like this

`
import { MessageBox } from 'react-chat-elements'

function App() {
  return (
    <MessageBox
      className="chat-color"
      title="Tobias"
      avatar={'https://cdn-icons-png.flaticon.com/512/727/727399.png'}
      onReplyMessageClick={() => console.log('reply clicked!')}
      position={'left'}
      type={'text'}
      text={'Let me know once you complete.'}
      replyButton={true}
      date={new Date()}
    />
  )
}`
