### ISSUE TITLE
MessageBox time is not editable

### ISSUE THREAD

**Issue by mystbrent** [Detaysoft/react-chat-elements#16]
#
<img width="278" alt="capture" src="https://user-images.githubusercontent.com/22728407/29627912-4d71b66c-8866-11e7-9b11-688fe7a8c509.PNG">

**Comment by abdurrahmanekr** [comment]
It may be 'forgotten points' because we are still in the beginning. So your feedback is very welcome.

**Comment by abdurrahmanekr** [comment]
Keep an eye out for our next release v0.4.5. You can follow along with updates #17

**Comment by mystbrent** [comment]
Sure thanks
