### ISSUE TITLE
IT DOESNT WORK ON REACT NATIVE AT ALL

### ISSUE THREAD

**Issue by bimix** [Detaysoft/react-chat-elements#168]
Please don't waste our time like this by mentioning in the documentation that it works in RN but in fact it doesnt.

**Comment by abdurrahmanekr** [comment]
Sorry for documentation. [commit](https://github.com/Detaysoft/react-chat-elements/commit/bb6b9266d4b722b1ad1803fec287128a2bb43e1e)
