### ISSUE TITLE
`onClick` of a button triggers all the time

### ISSUE THREAD

**Issue by Jak2k** [Detaysoft/react-chat-elements#169]
```
<Input
              placeholder="Type here..."
              multiline={true}
              onChange={this.handleChange.bind(this)}
              rightButtons={<Button color="white" backgroundColor="black" text="Send" onClick={console.log("Hi")/*chatProvider.sendChatMessage(this.props.id, this.state.input)*/} />}
            />
```
In my console there stands "Hi" very often. I don't clicked the button. I just write into the text field.

**Comment by kursatsmsek** [comment]
I got an error when I tried your code. I couldn't get a "Hi" message in the console after render. As a solution, arrow func. must be used in the onClick event;
onClick={() => console.log("Hi")}
Another idea is about the onChange event. If you get this error again please check your onChange event.
