### ISSUE TITLE
Some optional props declared as mandatory in IMessageListProps

### ISSUE THREAD

**Issue by destan** [Detaysoft/react-chat-elements#175]
`MessageList` component's type `IMessageListProps` requires following props as mandatory but they should be optional:

* `downButton`
* `downButtonBadge`
* `sendMessagePreview`

**Comment by destan** [comment]
Any comments on this? Are you willing to review & merge a PR if I make one?

**Comment by emregudur** [comment]
Hi, sorry for late, we fixed this issue on new version (12.0.6)
