### ISSUE TITLE
Autoplay attribute in AudioMessage

### ISSUE THREAD

**Issue by mgatto** [Detaysoft/react-chat-elements#176]
I want to have audio autoplay (subject to all the current browser constraints, of course). I tried an obvious way like this in a MessengerList, but it doesn't pick it up:

```
 {
    position: "right",
    type: "audio",
    title: "My ChatBot",
    text: `${data.bot_response.message}`,
    data: {
      autoplay: true,
      controlsList: "nodownload",
      audioURL: `http://127.0.0.1:5000/wav/${data.bot_response.audio_file}`,
    },
},
```

AudioMessage.tsx just expands the props.audioProps so how can I format the JSON to slip the autplay attribute in there?

`<audio {...props.audioProps} controls controlsList={controlsList ? controlsList : 'nodownload'}>`

**Comment by emregudur** [comment]
Hi, sorry for late. 
With this props: 
```javascript 
{
    id: '1',
    type: 'audio',
    date: new Date(),
    focus: false,
    forwarded: false,
    notch: false,
    position: 'right',
    removeButton: false,
    replyButton: false,
    retracted: false,
    status: 'read',
    text: 'text',
    title: 'title',
    titleColor: 'red',
    audioProps: {
      autoPlay: true,
    },
    data: {
      audioType: 'audio/wav',
      audioURL: '[some audio link].wav',
    },
  }

```
And I saw this result, you can see autoPlay props on developer tool: 

<img width="1341" alt="Ekran Resmi 2022-10-22 15 07 49" src="https://user-images.githubusercontent.com/41473129/197338567-4a0d379b-b089-4eb8-ab66-c05fae1701ef.png">
