### ISSUE TITLE
I can not find any way to make video icon in meetingLink.

### ISSUE THREAD

**Issue by S2econdBlue** [Detaysoft/react-chat-elements#178]
![image](https://user-images.githubusercontent.com/101093707/202893281-23fce3ad-b0f5-49e6-ab7e-e0e6ef569649.png)

 I don't know about react-native well, Is this elements doesn't work in react?

I want to do like title but I gave up. No way to add Icon.

![image](https://user-images.githubusercontent.com/101093707/202893611-6935721e-a861-4774-9775-e5b0381c353e.png)

above ref is good to use but meetingLink is no ref, no example, no code.. : ( : ( : ( : (

Sorry, I tired...

**Comment by emregudur** [comment]
Hi, you can see every property of components in [full documentation](https://detaysoft.github.io/docs-react-chat-elements/)
