### ISSUE TITLE
Why i need modify the file type.d.ts?

### ISSUE THREAD

**Issue by EdwinLoyolaTE** [Detaysoft/react-chat-elements#179]
I installed version 12.0.6, when I wanted to use the MessageBox component, it did not recognize the title, text, position properties.

When inquiring I saw that MessageBox extends from IMessageBoxProps.

But IMessageBoxProps does not extend IMessage. Add the extends IMessage line in IMessageBoxProps and it worked.
![extends](https://user-images.githubusercontent.com/95767058/206054490-abb0a06b-4b32-4f8b-9aca-9b23a1897c96.png)

![image](https://user-images.githubusercontent.com/95767058/206055312-a715320f-fd99-4c13-a221-006a5493f52a.png)

**Comment by emregudur** [comment]
Hi, can you try [this](https://github.com/Detaysoft/react-chat-elements/blob/08d97456e884431ee544fbfacc206d067c78a4aa/src/type.d.ts#L1083) type?

**Comment by sunshineo** [comment]
@emregudur if what you said
This line is wrong https://github.com/Detaysoft/react-chat-elements/blob/08d97456e884431ee544fbfacc206d067c78a4aa/src/type.d.ts#L1087
export class MessageBox extends React.Component<IMessageBoxProps> {}
should be
export class MessageBox extends React.Component<MessageBoxType> {}

**Comment by tresorama** [comment]
While waiting for a merged fix is it possible to "fix" in a consumer project without touching the `types.d.ts` in `node_modules` ?

I tried with a custom `fix.d.ts` file without success, if someone has code to show here it will be appreciated
