### ISSUE TITLE
how to clear the value in Input after submit input content?

### ISSUE THREAD

**Issue by ThinkCats** [Detaysoft/react-chat-elements#180]
here is my code:

```
<Input className="inputStyle"
        placeholder="please input your text ..."
        multiline={true}
        rightButtons={<Button text={"Send"} onClick={handleSubmit} title="Send" />}
        onChange={(data) => store.updateInputMsg(data.target.value)}
        referance={inputRef}
      />
```

here is about onClick function:
```javascript
  const handleSubmit = () => {
    store.sendWsMsg(store.inputMsg);
  
    //TODO how to reset input content
    // I tried this:
    // inputRef.target = {};
    //inputRef.value = '';
    // inputRef.defaultValue = '';
  }
```

**Comment by emregudur** [comment]
Like this;

New usage in **function component**: clearRef();

```diff

    import { Input } from 'react-chat-elements'
+    let clearRef = () => {};
    const inputReferance = React.useRef();

    <Input
    	referance={inputReferance}
+    	clear={(clear) => clearRef = clear}
    	placeholder="Type here..."
    	multiline={true}
    	.
    	.
    	.
    />

```

**Comment by tiagocredih** [comment]
`
import React, { useEffect, useState } from 'react'
import { MessageList, Input } from "react-chat-elements"
import {
  InputGroup,
  InputGroupAddon,
  Button,
} from 'reactstrap'
import moment from 'moment'

function Chat({ messages, sendMessage }) {
  const [message, setMessage] = useState('')
  const { user } = useLoggedUser()

  const pushMessage = (message) => {
    message = {
      position: "right",
      type: "text",
      title: user.username,
      text: message,
      date: moment().toDate(),
      dateString: moment().format('DD/MM HH:mm'),
    }

    setMessage('')
    sendMessage(message.text);
  };


  return (
    <div>
      <MessageList
        className='message-list'
        lockable={true}
        toBottomHeight={'100%'}
        dataSource={messages}
      />

      <InputGroup className='mt-5'>
        <Input
          className="form-control border-0 p-0"
          placeholder="Mensagem"
          multiline={true}
          autofocus={true}
          value={message}
          maxHeight={100}
          minHeight={46}
          onChange={e => {setMessage(e.target.value); console.log(setMessage + message)}}
        />

        <InputGroupAddon addonType="append">
          <Button
            color='primary'
            onClick={() => pushMessage(message)}
          >
            <span className="btn-inner--icon">
              <i className="fa fa-paper-plane" />
            </span>
          </Button>
        </InputGroupAddon>
      </InputGroup>
    </div>
  )
}

export default Chat
`

I still have problems with my code, could anyone help? I tried the last suggested solution but it didn't work.
