### ISSUE TITLE
How to render HTML in MessageList Component ?

### ISSUE THREAD

**Issue by nileshzala005** [Detaysoft/react-chat-elements#191]
MessageList allows only to render string but how display HTML in it ?

**Comment by camrail** [comment]
See [here](https://github.com/Detaysoft/react-chat-elements/issues/114)

**Comment by antun** [comment]
Is there a way to do this when you're passing a list of messages to the `MessageList` component like this:

```
<MessageList className='message-list' lockable={false} toBottomHeight={'100%'} dataSource={messages} />
```

(That's following the [example in the docs](https://detaysoft.github.io/docs-react-chat-elements/docs/messagelist). I don't actually see how to initialize the individual `MessageBox` items in the docs.)

If I put HTML in my `messages` array it just gets rendered as tags.
