### ISSUE TITLE
Please upgrade to react 18

### ISSUE THREAD

**Issue by ILG2021** [Detaysoft/react-chat-elements#195]
Hello, the react version is 17, not compatible with new project.

**Comment by saminightshift** [comment]
This has been mentioned before in this issue: https://github.com/Detaysoft/react-chat-elements/issues/171

**Comment by ILG2021** [comment]
Please upload to npm, thank you.

**Comment by o3osatoshi** [comment]
Hi @yamanSitech, @ILG2021

Sorry for the inadvertence. I changed the access control and it is public now.
If GitHub Packages are inconvenient for you, I will upload it to official npm.

**Comment by ILG2021** [comment]
No need. I can use --force. thanks
