### ISSUE TITLE
Avatar for the MessageBox

### ISSUE THREAD

**Issue by aliogaili** [Detaysoft/react-chat-elements#34]
Thanks for the great component!

I'm wondering if it's possible to add avatar to the messageBox, say we've multiple people in a chat room.

**Comment by abdurrahmanekr** [comment]
@aliogaili There doesn't seem to be a message avatar. I think it will be a great addition. Thanks for reporting!

**Comment by mlelyakan** [comment]
@aliogaili there is no avatar support for the messagebox component. We haven't done yet. Maybe you can use avatar and messagebox components inside a div tag by using flexbox temporarily. Thanks for reporting.

**Comment by aliogaili** [comment]
@mlelyakan I'm currently using the MessageList and passing the messages as data source (just like the example). So I was thinking that it'd be useful if we've an avatar prop that would allow us to add an arbitrary react component (typically an avatar) next to the arrow of the message. 

It's not critical at the moment since I can differentiate the author by the title of the message, although I really think a visual differentiation via an avatar will be a great addition.

Are you folks planning to add that?

**Comment by abdurrahmanekr** [comment]
This property has been added on #39

**Comment by Drtech-859** [comment]
messageBox avatar should be customizable so that the ui looks good
