### ISSUE TITLE
How to enable developement mode

### ISSUE THREAD

**Issue by supunucsc** [Detaysoft/react-chat-elements#54]
Hi, I'm new to react js and I want to enable developement mode of react-chat-elements which enable changes of source code will effect immediately to the code. Can you kindly support it?

**Comment by abdurrahmanekr** [comment]
Change the value of "main" in the package.json file:
```
"main": "src/index.js",
```
You should include react-chat-elements in your babel-loader.

**Comment by abdurrahmanekr** [comment]
Of course. 
```javascript
var path = require('path');

module.exports = {
    ...,
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: "babel-loader",
                include: [
                    path.join(__dirname, 'node_modules/react-chat-elements'),
                    ...
                ]
            },
            ...
        ]
    },
};
```

**Comment by supunucsc** [comment]
Hi thanks for the info. I edited the same file on react-chat-elements/webpack.config.js.  But still the error I encountered that error I posted.  Compiler error. on MessageList.js

**Comment by abdurrahmanekr** [comment]
No you have to make changes on your own project "webpack" file. You shouldn't do that in react-chat-elements.

**Comment by supunucsc** [comment]
Thanks but my project does not have webpack file.
