### ISSUE TITLE
Source code issue

### ISSUE THREAD

**Issue by supunucsc** [Detaysoft/react-chat-elements#55]
![image](https://user-images.githubusercontent.com/26418292/37377589-c8e991e0-2765-11e8-8365-d2fd5ab78d0f.png)

**Comment by abdurrahmanekr** [comment]
If you created your react-project by using create-react-app you need to work hard to do that. If you do your own project by using webpack you can change this kind of special cases.

If you wish you can take a look these links:
https://scotch.io/tutorials/setup-a-react-environment-using-webpack-and-babel
https://github.com/insin/nwb

**Comment by supunucsc** [comment]
I encounter that issue when I change package.json of react-chat-elements  main:src/index.js

![image](https://user-images.githubusercontent.com/26418292/37388573-06413e54-279c-11e8-8958-61b2701184f8.png)
Is that wrong approach? Any way to overcome this kindly? I want to change the source codes .
