### ISSUE TITLE
React Native TODO

### ISSUE THREAD

**Issue by abdurrahmanekr** [Detaysoft/react-chat-elements#61]
- [ ] All component props onClick events converted to onPress
- [ ] Components document for react-native.
- [ ] FileMessage component
- [ ] LocationMessage component
- [ ] PhotoMessage component
- [ ] SystemMessage component
- [ ] Input component
- [ ] ChatList component

**Comment by mitchobrian** [comment]
> why don't you create a single package called react-native-chat-elements?

sounds better than the current state!
do you have a more detailed plan when you're going to complete the tasks?

**Comment by salatielq** [comment]
Hello! it is ok if I work on the ChatList component? Are there any instructions to do the contribution?

**Comment by abdurrahmanekr** [comment]
Hi @salatielq, actually not :) In fact, it's okay to even rewrite the react-native logic. Because it's pretty useless. You are quite free about this and I would be very happy about it.

**Comment by salatielq** [comment]
Great then I will fork the repo and submit a PR later :)
