### ISSUE TITLE
Navbar only shows code in center attribute

### ISSUE THREAD

**Issue by Ironjanowar** [Detaysoft/react-chat-elements#63]
First of all, thanks for the library is super COOL!

My problem is that I'm trying to use the `Navbar` with the three attributes `top`, `center` and `bottom`, but only `center` is working. Here is the code:
```jsx
<Navbar
  top={
    <div>
      <strong>Something 1</strong>
    </div>
  }
  center={
    <div>
      <strong>Something 2</strong>
    </div>
  }
  bottom={
    <div>
      <strong>Something 3</strong>
    </div>
  }
/>
```

Only shows `Something 2` on screen
![image](https://user-images.githubusercontent.com/9699815/42516474-57caf5ac-845e-11e8-8ad2-0df7ff755659.png)
Here is a picture if it helps :sweat_smile: 

And I think the same thing happens with `SideBar`

**Comment by abdurrahmanekr** [comment]
> First of all, thanks for the library is super COOL!
Thanks

Oh now i've noticed.. The README.md file is incorrect. The correct use of it should be "left" and "right".

**Comment by abdurrahmanekr** [comment]
And.. fix. #64
