### ISSUE TITLE
moment is not a function

### ISSUE THREAD

**Issue by AndrewMerke** [Detaysoft/react-chat-elements#69]
Hello, I am getting error from MessageBox:

`Uncaught (in promise) TypeError: moment is not a function
    at MessageBox.render (main.js:1)`

I have moment lib installed into my project

I am using MessageBox with MessageList.

**Comment by abdurrahmanekr** [comment]
does the following list return when you run the following command in your project?
```
$ npm ls moment
├─┬ react-chat-elements@10.0.2
│ └── moment@2.22.2
```

**Comment by AndrewMerke** [comment]
Yes, exactly like you wrote

**Comment by demarchisd** [comment]
Same problem here.. 

@AndrewMerke did you solve it?
