### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by jamalabo1** [Detaysoft/react-chat-elements#80]
```react-chat-elements version: 10.0.5```
Issue: 
MessageBox Download button is not working, 

### Customization Request:
Change MessageBox style
onDownload (click) event with object supplied to the element

and there is a lot of things that can be customized.

**Comment by ryhnnl** [comment]
> MessageBox Download button is not working

@jamalabo1 can you give more details if you still have the issue?

**Comment by jamalabo1** [comment]
> > MessageBox Download button is not working
> 
> @jamalabo1 can you give more details if you still have the issue?

of course i still have it, its about updating the script, 

1) download button does not work
2) i can't even disable it

**Comment by ryhnnl** [comment]
@jamalabo1 I can see what is happening now. Which version are you using? I wanted to be sure if it is v10.0.5 or latest?

**Comment by ryhnnl** [comment]
> onDownload (click) event with object supplied to the element

 And I thought about this a little bit, you are giving the onDownload prop in the place which you can access the object data and you can use it in the onDownload prop. Passing an object through the component used for showing the data doesn't make sense in my opinion. :thinking: 

And there is MessageList component which does the exact thing you want. In MessageList component we are calling the click props (onDownload, onClick, etc) with parameters x (item), i (index of the item), and e (event).

**Comment by ryhnnl** [comment]
Here is an example for the download button. It works actually but understanding it takes time
First here is a message object template in this.state.messageList array
```
{
    ...
    type: 'photo',
    data: {
        ...
        uri: `data:image/png;base64,....`,
        status: {
            click: false,
            download: false,
        },
    }
}
```
For a photo message if you set `data.status.click` to `true` the download button shouldn't appear, you can think like it assumes that u have clicked it and downloading... 
And if you set `data.status.download` to `true` which means the photo downloaded, download button will not show up itself, if you set it `false` the photo will be a bit darker like a preview maybe. 

```
this.state.messageList.map(x =>
    <MessageBox
        {...x}
        onDownload={(e) => {
            x.data.status.click = true;
            // your download operation
            x.data.status.loading = 1;
            this.setState(this.state, () => {
                setTimeout(() => {
                    x.data.status.loading = false;
                    this.setState(this.state);
                }, 1000);
            });
        }}/>)
```

I hope it helps for now.

**Comment by jamalabo1** [comment]
@ryhnnl 
i'm trying to run `build` command but i does not work, 
can you tell me what Dependencies you are using to build the script
and how to build `src` only without `native` ?

**Comment by ryhnnl** [comment]
if you cloned the repo, start with `npm install` and you can run the example with `npm start`

**Comment by jamalabo1** [comment]
@ryhnnl 
im using the same repo (clone) and published it as `react-chat-elements-v2`, 

but i got the error 
```
ncaught Error: Module parse failed: Unexpected token (35:12)
You may need an appropriate loader to handle this file type.
| 
|         return (
>             <div
```

not im using `react-chat-elements` and its working fine.

**Comment by abdurrahmanekr** [comment]
Hi, if you don't want to change the structure completely, you don't need to open a repo like react-chat-elements-v2. 

You can contribute to the project by opening an MR (Merge Request) be able to add a new feature that you can do or want.

Also this is not a detailed description:
> download button does not work
> i can't even disable it

So, as far as I understand, the download button does not close when you press the download button and when you do the operation. 

> Solution:

"The problem is that you don't use dynamic data."

> How do we use data dynamically?

Suppose we keep a message list on "state". ex:

```javascript
import React, { Component } from 'react';
import 'react-chat-elements/dist/main.css';

import {
    MessageBox,
} from 'react-chat-elements';

class App extends Component {
    constructor(props){
        super(props);

        this.state = {
            messageList: [
                {
                    type: 'photo',
                    data: {
                        uri: 'https://avatars2.githubusercontent.com/u/69631?s=200&v=4',
                        status: {
                            click: false,
                            loading: 0,
                            download: false,
                        }
                    }
                },
            ]
        };

        this.onDownload = this.onDownload.bind(this);
    }

    onDownload(msg, event) {
        console.log('item onDownload click');

        // download process
        console.log('download process...');

        msg.data.status.download = true;
        msg.data.status.click = true;

        console.log('download success!');
        this.setState({
            messageList: this.state.messageList,
        })
    }

    render(){
        return (
            <div>
            {
                this.state.messageList.map(x => (
                    <MessageBox
                        type={x.type}
                        onDownload={event => this.onDownload(x, event)}
                        data={x.data}/>
                ))
            }
            </div>
        );
    }
}

export default App;
```
> Output

![download](https://user-images.githubusercontent.com/15075759/48330980-b6536380-e65f-11e8-9e76-5ebe33232181.gif)

### My Suggestion

You can use the component [MessageList](https://github.com/Detaysoft/react-chat-elements#messagelist-component) (like a onDownload, onOpen..) that executes these operations alone.
