### ISSUE TITLE
How to set the Google Map API key

### ISSUE THREAD

**Issue by JayathmaChathurangani** [Detaysoft/react-chat-elements#81]
I am trying to embed a map to my reactjs chat application.
```
<MessageBox
                                    avatar={this.state.avatarUrl}
                                    title={e.user}
                                    position={'left'}
                                    type={'location'}
                                    text={e.text}
                                    dateString={e.time}
                                    data= {{
                                        status: {
                                            click: true,
                                            loading: .5,
                                        },
                                        width: 300,
                                        height: 300,
                                        latitude: '37.773972',
                                        longitude: '-122.431297
                                    }}
                                    />
```
I am getting the error in the console,
staticmap:1 GET https://maps.googleapis.com/maps/api/staticmap?markers=color:red|37.773972,-122.431297&zoom=14&size=270x200&scale=2&key= 403

How to set the key and set the img?

**Comment by ryhnnl** [comment]
@JayathmaChathurangani  you can set the api key by giving apiKey prop to the component
```javascript
<MessageBox
        ...
        apiKey="your google api key"
/>
```

**Comment by JayathmaChathurangani** [comment]
That is about <LocationMessage/> component. Somehow I can see that key is set but the error is still there. 

GET https://maps.googleapis.com/maps/api/staticmap?markers=color:red|37.773972,-122.431297&zoom=14&size=270x200&scale=2&key=AIzaSyBtCWC9oI-qXh5ZgtN3NW28uNRKNw 403

**Comment by ryhnnl** [comment]
It is probably about your Google API key. Google is now betting only 1 request unless you specify billing. Take a look at these: 
[Google Maps Platform Pricing](https://cloud.google.com/maps-platform/pricing/)
[Google Maps Platform](https://cloud.google.com/blog/products/maps-platform/introducing-google-maps-platform)
