### ISSUE TITLE
is it possible to put videos, audios, maps, and images for react-native?

### ISSUE THREAD

**Issue by muhammadwfa** [Detaysoft/react-chat-elements#89]
Hello, I returned back from react-native-gifted-chat, because of slow loading messages and does not support audios and videos as well.

Now I need to know does supports this package video, audio and iamge?
is it possible to load chat messages faster?

**Comment by abdurrahmanekr** [comment]
Hello, this package does not have enough features on React Native. We need some features here #61  Feel free to submit a PR if @muhammadwfa or anyone else wants to submit a feature for this.
